In [1]:
from _linear import LinearRegression
import _dgp as dg
from _metrics import mse_score, CrossValidation, accuracy_score,f1_score
from  _logistic import LogisticRegression
import numpy as np
import pandas as pd

<h1>Linear Regression</h1>

Generate data with no correlation

In [2]:
x,y=dg.gen(type=1)
print(x.shape)
print(y.shape)

(500, 50)
(500,)


Run linear regression and get B parameter

In [3]:
#use Newton Raphson optimisation 
regression=LinearRegression(solver="nr")
regression.fit(x,y)

algorithm did  converge under 100 iterations (at 2 iterations)


array([ 2.23783647e-04,  2.49652850e+00,  1.30649029e+00,  5.03801576e-01,
       -5.02978053e-01, -3.39880934e+00, -3.78100145e-03,  1.40860902e-03,
        4.52349779e-03, -1.65757321e-03,  1.10668336e-03,  4.85344449e-03,
        4.29365967e-04,  3.88988139e-03, -2.35255808e-03,  3.80614797e-04,
        4.51589297e-04,  3.02106346e-04,  3.88246023e-04,  4.67030140e-04,
       -4.69914363e-03,  5.76274206e-03, -1.26583497e-03, -1.55583294e-03,
       -2.90865982e-03, -2.95237002e-03,  3.66758086e-03, -8.66169510e-03,
        7.59207489e-03, -8.03563259e-04, -1.01806651e-02, -8.25392961e-03,
        1.00665666e-02, -5.19047085e-03, -6.86093572e-03,  1.06657638e-02,
       -2.24394201e-03,  1.45246557e-03,  5.43490215e-03, -1.92395644e-04,
       -6.05702494e-03, -1.96389555e-03,  2.86759379e-03, -1.00381190e-04,
        7.15246003e-03, -6.37635620e-03,  2.70769664e-03,  1.09671587e-02,
       -4.43914703e-03, -3.48510539e-03,  1.51745084e-04])

As we used NR optimisations, it converged very fast, only in 2 iterations

if We want to interpret Linear regression results, we can do so by typing this command:

In [5]:
regression.get_inference().head()

params       std     t value  p value
0  0.000224  0.004589    0.048765   0.9611
1  2.496528  0.004787  521.516718   0.0000
2  1.306490  0.004461  292.860124   0.0000
3  0.503802  0.004649  108.366257   0.0000
4 -0.502978  0.004477 -112.347863   0.0000

In [17]:
res2=(y-regression.predict(x))**2
res2

array([1.80216499e-03, 1.93364135e-02, 8.46417908e-04, 9.26312579e-04,
       1.35612833e-02, 3.86853853e-02, 2.57430646e-03, 4.35111392e-03,
       6.25547943e-04, 1.10382778e-02, 3.10082009e-02, 6.94158080e-06,
       1.34894962e-02, 2.16346633e-02, 1.38718905e-02, 1.00809891e-03,
       1.75206917e-04, 8.67559209e-04, 1.67282854e-03, 4.90670370e-03,
       2.61373453e-02, 6.67259743e-03, 1.53114767e-05, 6.48034153e-02,
       5.31895293e-03, 9.52202041e-04, 6.53461102e-04, 3.91370598e-03,
       6.90395858e-04, 2.79176902e-03, 3.35915780e-02, 7.03472986e-03,
       1.13528976e-04, 1.92294285e-03, 2.92068690e-03, 1.30957035e-02,
       1.33155591e-03, 2.35757570e-02, 3.60510103e-02, 3.72746965e-02,
       2.08616144e-03, 7.53558303e-03, 2.69477135e-03, 2.47004428e-03,
       3.11733024e-04, 1.67895281e-04, 4.68854743e-03, 7.78795459e-03,
       1.30686297e-02, 2.01009068e-03, 4.62054675e-03, 1.36446213e-02,
       2.81180245e-03, 4.11864714e-03, 1.76118517e-02, 5.61980100e-04,
      

In [9]:
m=x.T@x
eigenvalues = np.linalg.eigvals(m)

In [11]:
np.sqrt(max(eigenvalues)/min(eigenvalues))

1.9002303680394352

BP

In [23]:
m=LinearRegression(solver="ols")
m.fit(x,res2)
scr=np.sum((res2-m.predict(x))**2)

In [25]:


sct=np.sum((res2-np.mean(res2))**2)
sce=sct-scr
x.shape[0]*sce/sct

61.088720624015735

VIF

In [27]:
for i in range(x.shape[1])
x[:,i]

array([-6.04455802e-02,  8.86064314e-02,  8.97254511e-01,  6.30514696e-01,
       -3.67753934e-01,  1.00418829e+00,  8.36262667e-01, -3.08065802e-01,
        1.11850194e+00,  1.48073131e+00, -4.62003877e-01,  2.05754498e-01,
        1.13475614e+00, -1.30370034e-01,  5.76337093e-01,  4.21141302e-01,
        1.17954288e-01, -9.65225009e-01, -1.63434011e+00, -2.67720629e-01,
        3.62679632e-02,  1.07815961e+00,  9.54154646e-01,  1.93031671e+00,
       -1.23847366e-01,  6.36461239e-01, -1.97400298e+00,  1.83531278e-01,
        4.55873177e-01,  6.14586613e-02, -1.48681407e+00, -5.69523914e-01,
       -3.57077608e-01,  3.62513575e-01, -6.21194226e-01,  5.88346763e-01,
       -1.97441421e+00, -1.78405776e+00,  1.90326755e-01,  7.89676080e-01,
       -6.72428074e-02,  1.28152527e+00, -1.52085408e+00, -3.81397166e-01,
        1.56170069e+00, -1.34142655e+00,  1.23106446e+00, -6.07183060e-01,
       -2.58028925e-01, -4.04712741e-01,  1.35276399e-01, -1.70075082e-01,
        2.19640321e+00,  

We can evaluate model performance by looking at MSE

In [17]:
mse_score(y,regression.predict(x))

0.007461950038721623

The best way to evaluate model performance remains Cross Validation

In [22]:
list_of_mse=CrossValidation(Class_algorithm=regression,x=x,y=y,metrics_function=mse_score,nb_k_fold=6)
print(list_of_mse)

algorithm did  converge under 100 iterations (at 2 iterations)
algorithm did  converge under 100 iterations (at 2 iterations)
algorithm did  converge under 100 iterations (at 2 iterations)
algorithm did  converge under 100 iterations (at 2 iterations)
algorithm did  converge under 100 iterations (at 2 iterations)
algorithm did  converge under 100 iterations (at 2 iterations)
algorithm did  converge under 100 iterations (at 2 iterations)
[0.008366650090492278, 0.008926335388529164, 0.009450567718380496, 0.011295040543736782, 0.009873535736372823, 0.009144819190386013, 0.0031046842380932516]


we can average these results to get average model performance

In [23]:
np.mean(list_of_mse)

0.008594518986570114

<h1>Logistic Regression</h1>

Load data and explore 

In [34]:
table=pd.read_csv("data/exampleLR.csv")

In [35]:
table

Unnamed: 0        V1        V2        V3        V4        V5  y
0             0 -0.560476 -0.601893 -0.995799 -0.820987 -0.511604  0
1             1 -0.230177 -0.993699 -1.039955 -0.307257  0.236938  0
2             2  1.558708  1.026785 -0.017980 -0.902098 -0.541589  1
3             3  0.070508  0.751061 -0.132175  0.627069  1.219228  0
4             4  0.129288 -1.509167 -2.549343  1.120355  0.174136  0
..          ...       ...       ...       ...       ...       ... ..
495         495 -1.358079 -0.089975  0.214479  0.076644  0.726564  1
496         496  0.181847  1.070516  0.892571  0.255165  1.440870  1
497         497  0.164841 -1.351100  1.018758  0.277447 -0.210170  0
498         498  0.364115 -0.522617  1.089112  0.536856  1.451281  0
499         499  0.552158 -0.249191 -0.163129 -0.460486  0.641551  0

[500 rows x 7 columns]

Always convert data to numpy array

In [60]:
x,y=np.array(table.drop(["y","Unnamed: 0"],axis=1)),np.array(table["y"])

see if classes are balanced , in this case they are, so use of accuracy is enough

In [81]:
table["y"].value_counts()

y
0    253
1    247
Name: count, dtype: int64

Try Gradient Descent algorithm

In [61]:
model=LogisticRegression(solver="gd")
model.fit(x,y)

algorithm did not converge under 100 iterations,so the calculated parameter is biased


array([-0.1248317 , -0.98031107,  1.93586459,  0.89773156,  0.7761705 ,
       -1.07133784])

Algorithm could not converge, so the estimated parameter is biased, so try other hyperparameters to aim convergence

In [67]:
model1=LogisticRegression(solver="gd",learning_rate=0.004,max_iteration=300)
model1.fit(x,y)

algorithm did  converge under 300 iterations (at 79 iterations)


array([-0.14211795, -1.10847242,  2.18459166,  1.02655283,  0.87139786,
       -1.20943036])

Try stochastic gradient descent with 68 as size of mini batch to see the performance

In [68]:
model2=LogisticRegression(solver="sgd",learning_rate=0.001,max_iteration=300,mini_batch_size=68,add_intercept=False)
model2.fit(x,y)

algorithm did  converge under 2400 iterations (at 1080 iterations)


array([-1.03254695,  2.03007399,  0.9448015 ,  0.80938114, -1.11919829])

With new learning rate algorithm converged so we will use results of model1 to make predictions

In [72]:
model1.predict(x)[0:10]

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 1])

as well as get parameters significance

In [76]:
print(model1.get_inference())
print(model1.criteria)

     params       std   t value  p value
0 -0.142118  0.133005 -1.068517   0.2858
1 -1.108472  0.159209 -6.962360   0.0000
2  2.184592  0.222661  9.811274   0.0000
3  1.026553  0.163791  6.267456   0.0000
4  0.871398  0.144580  6.027095   0.0000
5 -1.209430  0.173253 -6.980720   0.0000
{'LL': -177.40450034974413, 'AIC_ll': 366.80900069948825, 'BIC_ll': 392.0966492900214}


Evaluate model with accuracy and f1score 

In [79]:
CrossValidation(Class_algorithm=model1,x=x,y=y,metrics_function=accuracy_score,nb_k_fold=4)

algorithm did  converge under 300 iterations (at 122 iterations)
algorithm did  converge under 300 iterations (at 86 iterations)
algorithm did  converge under 300 iterations (at 101 iterations)
algorithm did  converge under 300 iterations (at 95 iterations)


[0.8, 0.904, 0.816, 0.864]

In [80]:
CrossValidation(Class_algorithm=model1,x=x,y=y,metrics_function=f1_score,nb_k_fold=4)

algorithm did  converge under 300 iterations (at 114 iterations)
algorithm did  converge under 300 iterations (at 94 iterations)
algorithm did  converge under 300 iterations (at 99 iterations)
algorithm did  converge under 300 iterations (at 96 iterations)


[0.7839999999999999, 0.8925619834710744, 0.832, 0.8480000000000001]

<h1>Logistic Regression OVR

Load data

In [85]:
table=pd.read_csv("data/exampleLRMulti.csv")

Get rid of unnamed columns

In [87]:
table.drop(table.columns[table.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)

One more time classes are distributed equally, so we can estimate model performance with accuracy score

In [91]:
table["column_Y"].value_counts()

column_Y
1    336
0    333
2    331
Name: count, dtype: int64

In [92]:
x,y=np.array(table.drop(["column_Y"],axis=1)),np.array(table["column_Y"])

Estimate Multiclass Logistic Regression with One vs Rest algorithm and Newton Raphson optimisation 

Since it's an OVR algorithm, it will run model 3 times, this is why we have 3 converges in a row and 3 columns of B parameter

In [93]:
modelOVR=LogisticRegression(solver="nr",multiclass="ovr")
modelOVR.fit(x,y)

algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)


array([[-1.01498187, -1.45620846, -0.78718645],
       [ 0.34446018,  0.56751748, -0.79115877],
       [ 0.22977187, -0.65556071,  0.56300868],
       [ 0.05302252, -0.03242775, -0.03517929],
       [ 0.06803143,  0.15324563, -0.1736295 ],
       [-0.44905806,  0.79972167, -0.42289584],
       [ 0.02949896, -0.09727438,  0.07434896],
       [-0.64703364,  0.23914131,  0.39520493],
       [-0.03647586,  0.15863365, -0.09606587],
       [ 0.6808661 , -0.45149573, -0.23001672],
       [-0.01179362, -0.05067621,  0.03836354]])

We can also predict. Predictions are made always in the ascending order: 

    -first column will be 0 class
    -second column will be 1 class
    -third column will be 3 class


In [100]:
predictionsOVR=modelOVR.predict(x)
predictionsOVR 

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

We will compare these predictions to true one hot encoded labels

In [101]:
modelOVR.true_labels_matrix

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       ...,
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1]])

Of course, we can always get probability (for OVR it is not normalised, but for predicted values it is normalised!!)

In [102]:
modelOVR.proba

array([[0.14660444, 0.94592762, 0.01074276],
       [0.26867955, 0.36961135, 0.19349834],
       [0.0519826 , 0.32131164, 0.59426132],
       ...,
       [0.02941952, 0.15974979, 0.77393711],
       [0.26880729, 0.33355668, 0.22603021],
       [0.03407864, 0.33402281, 0.64490065]])

We can evaluate accuracy

In [104]:
accuracy_score(predictionsOVR, modelOVR.true_labels_matrix)

0.695

But we want more intelligent evaluation, so we use cross validation 

In [107]:
acc_list=CrossValidation(Class_algorithm=modelOVR,x=x,y=modelOVR.true_labels_matrix,metrics_function=accuracy_score,nb_k_fold=8)

algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iterations)
algorithm did  converge under 100 iterations (at 5 iter

By averaging we get more "robust" accuracy 

In [108]:
print(acc_list)
np.mean(acc_list)

[0.68, 0.632, 0.68, 0.704, 0.696, 0.696, 0.624, 0.672]


0.6729999999999999

<h1>Logistic Regression Softmax</h1>

Now, let's see another way of solving multicase without running P independent classifiers-> logistic softmax!

In [115]:
modelSFT=LogisticRegression(solver="gd",multiclass="softmax")#dont use nr for the moment
modelSFT.fit(x,y)

algorithm did  converge under 100 iterations (at 50 iterations)


array([[ 0.04194506, -0.27091767,  0.22897262],
       [ 0.23740402,  0.34859258, -0.58599659],
       [ 0.08908508, -0.4494452 ,  0.36036012],
       [ 0.0417117 , -0.02254157, -0.01917013],
       [ 0.03704339,  0.08616513, -0.12320852],
       [-0.27315999,  0.56539992, -0.29223993],
       [ 0.01838198, -0.07586092,  0.05747895],
       [-0.47306334,  0.21607495,  0.2569884 ],
       [-0.03294754,  0.10874983, -0.07580229],
       [ 0.48652451, -0.33256412, -0.15396038],
       [-0.00460555, -0.02954451,  0.03415006]])

We can compare them to modelOVR parameters

In [112]:
modelOVR.params

array([[-1.01498187, -1.45620846, -0.78718645],
       [ 0.34446018,  0.56751748, -0.79115877],
       [ 0.22977187, -0.65556071,  0.56300868],
       [ 0.05302252, -0.03242775, -0.03517929],
       [ 0.06803143,  0.15324563, -0.1736295 ],
       [-0.44905806,  0.79972167, -0.42289584],
       [ 0.02949896, -0.09727438,  0.07434896],
       [-0.64703364,  0.23914131,  0.39520493],
       [-0.03647586,  0.15863365, -0.09606587],
       [ 0.6808661 , -0.45149573, -0.23001672],
       [-0.01179362, -0.05067621,  0.03836354]])

also predict

In [113]:
modelSFT.predict(x)

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [116]:
meansftmx=CrossValidation(Class_algorithm=modelSFT,x=x,y=modelSFT.true_labels_matrix,metrics_function=accuracy_score,nb_k_fold=4)
np.mean(meansftmx)

algorithm did  converge under 100 iterations (at 65 iterations)
algorithm did  converge under 100 iterations (at 66 iterations)
algorithm did  converge under 100 iterations (at 56 iterations)
algorithm did  converge under 100 iterations (at 62 iterations)


0.671

Further steps:

 -introduce Newton Raphson for softmax regression

 -explore further inference statistics ( log odds, inference for multinomial logistic regressions)

 -do automatic variable selection ( stepwise, backward..., lasso..)
 
 -do real project using all these developped algorithms



In [118]:
modelSFT=LogisticRegression(solver="nr",multiclass="softmax")#dont use nr for the moment
modelSFT.fit(x,y)

ValueError: not done yet,incoming